export const locations = [
  { id: "Mitte", title: { de: "Mitte", en: "Mitte" } },
  { id: "Friedrichshain-Kreuzberg", title: { de: "Friedrichshain-Kreuzberg", en: "Friedrichshain-Kreuzberg" } },
  { id: "Pankow", title: { de: "Pankow", en: "Pankow" } },
  { id: "Charlottenburg-Wilmersdorf", title: { de: "Charlottenburg-Wilmersdorf", en: "Charlottenburg-Wilmersdorf" } },
  { id: "Spandau", title: { de: "Spandau", en: "Spandau" } },
  { id: "Steglitz-Zehlendorf", title: { de: "Steglitz-Zehlendorf", en: "Steglitz-Zehlendorf" } },
  { id: "Tempelhof-Schöneberg", title: { de: "Tempelhof-Schöneberg", en: "Tempelhof-Schöneberg" } },
  { id: "Neukölln", title: { de: "Neukölln", en: "Neukölln" } },
  { id: "Treptow-Köpenick", title: { de: "Treptow-Köpenick", en: "Treptow-Köpenick" } },
  { id: "Marzahn-Hellersdorf", title: { de: "Marzahn-Hellersdorf", en: "Marzahn-Hellersdorf" } },
  { id: "Lichtenberg", title: { de: "Lichtenberg", en: "Lichtenberg" } },
  { id: "Reinickendorf", title: { de: "Reinickendorf", en: "Reinickendorf" } },
  { id: "Remotely", title: { de: "Remotely", en: "Remotely" } },
];
