export const locations = [
  { id: "Mitte", title: { de: "Mitte", en: "Mitte" } },
  { id: "Moabit", title: { de: "Moabit", en: "Moabit" } },
  { id: "Wedding", title: { de: "Wedding", en: "Wedding" } },
  {
    id: "Friedrichshain",
    title: { de: "Friedrichshain", en: "Friedrichshain" },
  },
  { id: "Kreuzberg", title: { de: "Kreuzberg", en: "Kreuzberg" } },
  { id: "Pankow", title: { de: "Pankow", en: "Pankow" } },
  {
    id: "Prenzlauer Berg",
    title: { de: "Prenzlauer Berg", en: "Prenzlauer Berg" },
  },
  { id: "Weißensee", title: { de: "Weißensee", en: "Weißensee" } },
  {
    id: "Charlottenburg",
    title: { de: "Charlottenburg", en: "Charlottenburg" },
  },
  { id: "Wilmersdorf", title: { de: "Wilmersdorf", en: "Wilmersdorf" } },
  { id: "Spandau", title: { de: "Spandau", en: "Spandau" } },
  { id: "Steglitz", title: { de: "Steglitz", en: "Steglitz" } },
  { id: "Zehlendorf", title: { de: "Zehlendorf", en: "Zehlendorf" } },
  { id: "Tempelhof", title: { de: "Tempelhof", en: "Tempelhof" } },
  { id: "Schöneberg", title: { de: "Schöneberg", en: "Schöneberg" } },
  { id: "Neukölln", title: { de: "Neukölln", en: "Neukölln" } },
  { id: "Treptow", title: { de: "Treptow", en: "Treptow" } },
  { id: "Köpenick", title: { de: "Köpenick", en: "Köpenick" } },
  { id: "Marzahn", title: { de: "Marzahn", en: "Marzahn" } },
  { id: "Hellersdorf", title: { de: "Hellersdorf", en: "Hellersdorf" } },
  { id: "Lichtenberg", title: { de: "Lichtenberg", en: "Lichtenberg" } },
  { id: "Reinickendorf", title: { de: "Reinickendorf", en: "Reinickendorf" } },
  { id: "Tegel", title: { de: "Tegel", en: "Tegel" } },
  { id: "Rudow", title: { de: "Rudow", en: "Rudow" } },
  { id: "Remotely", title: { de: "Remotely", en: "Remotely" } },
];
