import { OpportunityApi } from "./tempTypes";

export const mockRawOpportunities = [
  {
    id: 5923,
    title: "Support for language café for women",
    vo_information: "Every Wednesday 12-13 o'clock, language café with women",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Kreuzberg"],
    schedule_str:
      "Monday 11-14, Tuesday 11-14, Thursday 11-14, Friday 11-14, Wednesday 11-14, Occasional Weekdays, Saturday 11-14, Sunday 11-14",
    datetime_str: null,
    timeslots: [
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 2,
        time_slot: "11-14",
      },
      {
        day: 4,
        time_slot: "11-14",
      },
      {
        day: 5,
        time_slot: "11-14",
      },
      {
        day: 3,
        time_slot: "11-14",
      },
      {
        day: 6,
        time_slot: "11-14",
      },
      {
        day: 7,
        time_slot: "11-14",
      },
    ],
    activities: ["Language café"],
    languages: ["Arabic", "English", "German", "Farsi", "Russian", "Turkish"],
    skills: ["Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:51.684970Z",
    updated_at: "2025-12-23T18:29:56.440438Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-23T15:32:00Z",
  },
  {
    id: 5925,
    title: "Literacy and learning German with women",
    vo_information:
      "The women want a low-threshold offer, guided by a volunteer who speaks and can write German. It should take place during the day. There is a common room with a whiteboard at the property. The volunteer is trained and has a permanent contact person from the main office team.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Neukölln"],
    schedule_str: "Monday 11-14, Tuesday 11-14, Thursday 11-14, Friday 11-14, Wednesday 11-14",
    datetime_str: null,
    timeslots: [
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 2,
        time_slot: "11-14",
      },
      {
        day: 4,
        time_slot: "11-14",
      },
      {
        day: 5,
        time_slot: "11-14",
      },
      {
        day: 3,
        time_slot: "11-14",
      },
    ],
    activities: ["Language café"],
    languages: ["Arabic", "English", "German"],
    skills: ["Teaching", "Public speaking"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:52.862979Z",
    updated_at: "2025-12-23T18:29:56.651608Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-23T15:32:00Z",
  },
  {
    id: 4356,
    title: "Radiology support (back and forth) WITHOUT translation from a doctor",
    vo_information: null,
    accomp_information:
      "Ms. Prima, a 71-year-old refugee from Ukraine, must be picked up at the reception of her accommodation at around 12:00 and accompanied to her doctor's appointment (approx. 1 hour and 20 minute drive). An interpreter is waiting for the resident at the entrance to the radiology department. The appointment concerns a short radiological examination. Ms. Prima then needs an escort back to the accommodation.",
    accomp_translation: "noTranslation",
    accomp_datetime: "2025-11-19T12:45:00Z",
    berlin_locations: ["Charlottenburg"],
    schedule_str: "",
    datetime_str: null,
    timeslots: [],
    activities: ["Accompanying to doctors'"],
    languages: [],
    skills: [],
    status: "Search in process",
    opportunity_type: "accompanying",
    created_at: "2025-11-07T16:00:09.647251Z",
    updated_at: "2025-11-07T16:34:10.888323Z",
    category: "Accompany a Refugee",
    category_id: 6,
    last_edited_time_notion: "2025-11-07T15:34:00Z",
  },
  {
    id: 5502,
    title: "German/math tutoring for ninth grade",
    vo_information: "We are looking for a person who could give individual lessons in German/math. ",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Kreuzberg"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Assist with homework"],
    languages: ["German"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-16T09:00:15.878857Z",
    updated_at: "2025-12-16T09:17:39.745166Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-16T08:17:00Z",
  },
  {
    id: 5729,
    title: "Volunteers to supervise the bicycle repair shop",
    vo_information:
      "In the property, we have an equipped room for bicycle repairs. We would like someone to come reliably once a week from 16:00 or on weekends.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Neukölln"],
    schedule_str:
      "Wednesday 14-17 | 17-20, Monday 14-17 | 17-20, Tuesday 14-17 | 17-20, Thursday 14-17 | 17-20, Friday 14-17 | 17-20, Saturday 14-17 | 17-20, Sunday 14-17 | 17-20",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
      {
        day: 6,
        time_slot: "14-17",
      },
      {
        day: 7,
        time_slot: "14-17",
      },
      {
        day: 6,
        time_slot: "17-20",
      },
      {
        day: 7,
        time_slot: "17-20",
      },
    ],
    activities: ["Miscellanious"],
    languages: ["Arabic", "German", "Farsi"],
    skills: ["Football", null],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-19T17:00:10.173656Z",
    updated_at: "2025-12-19T17:05:11.705495Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-19T16:01:00Z",
  },
  {
    id: 5926,
    title: "Support for the children's club",
    vo_information:
      "It can be one or two afternoons a week. Since we are flexible for this, I have marked days that are eligible. The person should be structured and open, and may also be able to help with homework.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Monday 14-17, Tuesday 14-17, Thursday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
    ],
    activities: ["Daycare"],
    languages: ["German"],
    skills: ["Public speaking"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:52.957870Z",
    updated_at: "2025-12-23T18:29:56.829670Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-23T15:32:00Z",
  },
  {
    id: 5927,
    title: "Childcare in the accommodation ",
    vo_information:
      "Together with the childcare team, volunteers spend time with the children in the accommodation and arrange leisure activities such as crafts, painting, etc. Volunteers are also happy to assist with events and trips.\nThe times: Mondays 13:30-17:00; Wednesdays 13:00-16:00",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Monday 14-17 | 11-14, Tuesday 14-17 | 11-14",
    datetime_str: null,
    timeslots: [
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 2,
        time_slot: "11-14",
      },
    ],
    activities: ["Daycare"],
    languages: ["English", "German"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:53.055921Z",
    updated_at: "2025-12-23T18:29:57.053943Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-23T15:32:00Z",
  },
  {
    id: 5928,
    title: "Childcare & crafts",
    vo_information: "Child care, crafts such as painting, and other activities for children staying at the property.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Spandau"],
    schedule_str: "Wednesday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Arts & Crafts"],
    languages: ["Arabic", "English", "French", "German", "Farsi", "Russian", "Turkish"],
    skills: ["Drawing", "Painting", "Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:53.150569Z",
    updated_at: "2025-12-23T18:29:57.272891Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-23T15:32:00Z",
  },
  {
    id: 5875,
    title: "Route assistance to the doctor/vascular surgeon",
    vo_information: null,
    accomp_information:
      "Ms. Shypko is doing poorly, so more time is planned for the journey. The appointment on site is at 9.45 a.m. An interpreter can be ordered on site for the appointment.\nMrs. Shypko also needs the escort back. So I think they should set aside 3 hours.\nFrom the social worker: Ms. Shypko doesn't have a current phone number, so I've given my number just to be on the safe side. If I don't answer, the call is automatically forwarded to my colleagues.",
    accomp_translation: "deutsche",
    accomp_datetime: "2026-01-08T07:15:00Z",
    berlin_locations: ["Lichtenberg"],
    schedule_str: "",
    datetime_str: null,
    timeslots: [],
    activities: ["Accompanying to doctors'"],
    languages: ["Russian", "Ukrainian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "accompanying",
    created_at: "2025-12-23T15:00:25.759437Z",
    updated_at: "2025-12-23T15:58:07.491212Z",
    category: "Accompany a Refugee",
    category_id: 6,
    last_edited_time_notion: "2025-12-23T14:25:00Z",
  },
  {
    id: 5653,
    title: "Co-direction for Frauen-Sprachcafe",
    vo_information:
      "There is already an experienced volunteer who is planning the language cafe. We are looking for a native German speaker who has time and desire to look after the café together on Tuesday afternoons from 15-16:30. No teaching experience is necessary.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Prenzlauer Berg"],
    schedule_str: "Tuesday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 2,
        time_slot: "14-17",
      },
    ],
    activities: ["Language café"],
    languages: ["German"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T12:00:10.725444Z",
    updated_at: "2025-12-18T12:28:25.481013Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-18T11:09:00Z",
  },
  {
    id: 5594,
    title: "Volunteers for hurdle jumpers in Tempelhof-Schöneberg",
    vo_information: "It is a long-term program that requires serious volunteer development.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Schöneberg", "Tempelhof"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Mentorship"],
    languages: ["German"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-17T15:00:17.562541Z",
    updated_at: "2025-12-17T15:02:43.539868Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-17T14:04:00Z",
  },
  {
    id: 5628,
    title: "Volunteers wanted for KiezTandems!",
    vo_information:
      "The KIEZTANDEM brings together people with refugee and migration experience and interested volunteers who have been living in Berlin for a long time. Depending on your interests and hobbies, we, the full-time team, will find a suitable tandem partner. As godparents, the volunteers help immigrants find their way and cope with everyday life in their new living environment, for example by exploring the neighborhood together, spending free time together, learning the German language or going to the authorities. The tandems spend 2-3 hours a week. The full-time team accompanies the tandems and organizes exchange meetings, training courses and trips for the tandems and interested parties. The team is also responsible for the matching process and accompanying sponsorships. The project staff are contact persons for questions, problems, ideas, etc. Requirements for involvement in KIEZTANDEM: They must be at least 18 years old; be interested in intercultural dialogue; there should be a willingness to participate in qualification seminars; they should enjoy exchanging ideas and joint activities. Volunteer tandem partners do not have to be trained specialists or social workers.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Köpenick", "Treptow"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Mentorship"],
    languages: ["German"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T11:00:14.252877Z",
    updated_at: "2025-12-18T11:26:40.024361Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-18T10:19:00Z",
  },
  {
    id: 5934,
    title: "language teachers",
    vo_information: "A person who offers a literacy course in German or Russian for women without basic knowledge.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Charlottenburg"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Assist with homework"],
    languages: ["Armenian", "German", "Russian", "Ukrainian"],
    skills: ["Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T17:00:16.250718Z",
    updated_at: "2025-12-23T18:29:57.768560Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-23T16:04:00Z",
  },
  {
    id: 5336,
    title: "weekly shopping for two brothers with disabilities",
    vo_information:
      "We are looking for regular shopping assistance for the two of them as they are physically unable to go shopping.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Zehlendorf"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Miscellanious"],
    languages: ["Arabic"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-10T16:00:13.045034Z",
    updated_at: "2025-12-10T17:09:03.985443Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-10T15:25:00Z",
  },
  {
    id: 5663,
    title: "Homework help",
    vo_information:
      "Help with homework and perfecting their German language skills (Wednesday and Thursday from 14:30 to 17:30). We have 2 rooms, 1 children's room and 1 homework room where homework help can take place.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Spandau"],
    schedule_str: "Wednesday 14-17, Thursday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["German", "Farsi", "Turkish", "Ukrainian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T14:00:33.970353Z",
    updated_at: "2025-12-18T14:03:04.062688Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-18T13:48:00Z",
  },
  {
    id: 5666,
    title: "NEW Telephone and personal translation DE-FR ",
    vo_information:
      "For a young man from Benin and talks with the supervisors, I am looking for a person who can translate important appointments.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Zehlendorf"],
    schedule_str: "Monday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Translation at Accommodation Centers"],
    languages: ["French", "German"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T14:00:37.185074Z",
    updated_at: "2025-12-18T14:03:04.364123Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-18T13:55:00Z",
  },
  {
    id: 5662,
    title: "NEW Homework help for a young man attending a language course",
    vo_information:
      "Young man with A1 language level is looking for regular support in learning for the language course.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Köpenick"],
    schedule_str: "Wednesday 14-17, Monday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17, Occasional Weekdays",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["German", "Farsi"],
    skills: ["Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T14:00:33.875121Z",
    updated_at: "2025-12-18T14:03:03.951412Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-18T13:28:00Z",
  },
  {
    id: 5899,
    title: "Volunteers and volunteers for BENN Mierendorffinsel",
    vo_information:
      "We are looking for volunteers who would like to support the following activities with us in the WERK-RAUM and in the common room:\n- bicycle workshop every Tuesday 4 - 6 p.m.;\n- sewing workshop every Thursday 4pm-6pm;\n- Language café every Wednesday 16:30-18:00 in the common room.\nAt the language café, we are looking for volunteers to moderate the language café (preferably a person who speaks German, Arabic and/or Turkish) and we are also looking for volunteers to provide childcare during the language café so that even more people (in care work) can participate.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Charlottenburg"],
    schedule_str: "Wednesday 14-17 | 17-20, Tuesday 14-17 | 17-20, Thursday 14-17 | 17-20",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
    ],
    activities: ["Miscellanious"],
    languages: ["Arabic", "French", "German", "Farsi", "Turkish", "Ukrainian"],
    skills: ["Woodworking", "Sewing", "Knitting", "Repairs", "Carpentry", null],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:31.649169Z",
    updated_at: "2025-12-23T18:29:58.425793Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-23T15:29:00Z",
  },
  {
    id: 5532,
    title: "Sprachcafé",
    vo_information:
      "Low-threshold help for residents. You speak A1.2-B1 German and would like to improve your German language skills. The language café can take place in the German course room. ",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Wednesday 14-17, Monday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Language café"],
    languages: ["Arabic", "Dari", "English", "German", "Farsi", "Russian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-16T15:00:19.469468Z",
    updated_at: "2025-12-16T15:37:44.099397Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-16T14:08:00Z",
  },
  {
    id: 5922,
    title: "Setting up a men's café with games and trips",
    vo_information:
      "We are looking for volunteers who would like to set up and run a men's café in the accommodation. The men's café should be a place for exchange, board games and being there. Excursions are also included, of course. ",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Kreuzberg"],
    schedule_str:
      "Wednesday 14-17 | 17-20 | 11-14 | 08-11, Monday 14-17 | 17-20 | 11-14 | 08-11, Tuesday 14-17 | 17-20 | 11-14 | 08-11, Thursday 14-17 | 17-20 | 11-14 | 08-11, Friday 14-17 | 17-20 | 11-14 | 08-11, Saturday 14-17 | 17-20 | 11-14 | 08-11, Sunday 14-17 | 17-20 | 11-14 | 08-11, Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 2,
        time_slot: "11-14",
      },
      {
        day: 4,
        time_slot: "11-14",
      },
      {
        day: 5,
        time_slot: "11-14",
      },
      {
        day: 6,
        time_slot: "14-17",
      },
      {
        day: 7,
        time_slot: "14-17",
      },
      {
        day: 3,
        time_slot: "11-14",
      },
      {
        day: 1,
        time_slot: "08-11",
      },
      {
        day: 2,
        time_slot: "08-11",
      },
      {
        day: 3,
        time_slot: "08-11",
      },
      {
        day: 4,
        time_slot: "08-11",
      },
      {
        day: 5,
        time_slot: "08-11",
      },
      {
        day: 6,
        time_slot: "17-20",
      },
      {
        day: 7,
        time_slot: "17-20",
      },
      {
        day: 6,
        time_slot: "11-14",
      },
      {
        day: 7,
        time_slot: "11-14",
      },
      {
        day: 6,
        time_slot: "08-11",
      },
      {
        day: 7,
        time_slot: "08-11",
      },
    ],
    activities: ["Activities for men"],
    languages: ["Arabic", "English", "Georgian", "German", "Farsi", "Russian", "Turkish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:51.559292Z",
    updated_at: "2025-12-23T18:29:56.234250Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-23T15:32:00Z",
  },
  {
    id: 5632,
    title: "Design activities for men in Neukölln",
    vo_information:
      "Arrive, understand, participate. Breaking new ground together: men's project by GBZ e.V. Refugee men in Berlin face a variety of challenges: understanding social norms, barriers to integration or the feeling of isolation. This is exactly where our men's project comes in. It creates a protected space for orientation, exchange and education — with the aim of facilitating social participation and opening up new perspectives. \n",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Neukölln"],
    schedule_str: "Occasional Weekdays",
    datetime_str: null,
    timeslots: [],
    activities: ["Activities for men"],
    languages: ["Arabic", "English", "German", "Farsi", "Russian", "Turkish"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T11:00:17.371904Z",
    updated_at: "2025-12-18T11:26:40.403483Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-18T10:19:00Z",
  },
  {
    id: 5908,
    title: "Helper at BENN Louis-Lewin-Straße",
    vo_information:
      "We are looking for assistance in moderating or translating discussions in our offerings and in guiding or accompanying creative hobbies such as crafting, crocheting or sewing. Our offerings also include spending time with neighbors, playing board games and having stimulating conversations.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Hellersdorf"],
    schedule_str: "Wednesday 14-17, Thursday 14-17 | 17-20, Occasional Weekdays",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
    ],
    activities: ["Miscellanious"],
    languages: ["Arabic", "English", "French", "German", "Farsi", "Polish", "Turkish", "Ukrainian", "Vietnamese"],
    skills: [
      "Drawing",
      "Painting",
      "Sewing",
      "Knitting",
      "Repairs",
      "Cooking",
      "Teaching",
      "Public speaking",
      "Gardening",
      "Decorating",
      "Photography",
      "Videography",
      "Dance",
      "Chess",
      "Management",
      "Mediation",
      "Guitar",
      "Singing",
      null,
    ],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:35.166870Z",
    updated_at: "2025-12-23T18:29:59.400655Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-23T15:30:00Z",
  },
  {
    id: 5338,
    title: "Help to fill out documents",
    vo_information:
      "* Always at fixed times - depending on your preferences (always only on weekdays, not on weekends) ",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Charlottenburg", "Wilmersdorf"],
    schedule_str: "Occasional Weekdays",
    datetime_str: null,
    timeslots: [],
    activities: [null],
    languages: ["Arabic", "English", "French", "German", "Farsi", "Russian", "Turkish"],
    skills: ["Football", null],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-10T17:00:09.312481Z",
    updated_at: "2025-12-10T17:09:04.680896Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-10T16:31:00Z",
  },
  {
    id: 5339,
    title: "Sport with boys (9-13 years)",
    vo_information:
      "We are looking for male volunteers to help with sports activities for 2-3 hours in the afternoon. Our accommodation has a children's room, a large courtyard with garden and nearby playgrounds and leisure activities.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Mitte"],
    schedule_str: "Wednesday 14-17, Monday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Sports"],
    languages: ["Arabic", "English", "German", "Farsi", "Polish", "Spanish"],
    skills: ["Fitness", "Basketball", null],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-10T17:00:10.773464Z",
    updated_at: "2025-12-10T17:09:04.970766Z",
    category: "Sport activities",
    category_id: 5,
    last_edited_time_notion: "2025-12-10T16:38:00Z",
  },
  {
    id: 5913,
    title: "Activities for teens (13-18 years)",
    vo_information:
      "Since September, we have had a youth cellar. We need volunteers who would like to do something with the teens (13-18 years), such as movie nights, playing soccer or board games, trips, cooking or crafts.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Schöneberg", "Tempelhof"],
    schedule_str:
      "Wednesday 14-17 | 17-20, Monday 14-17 | 17-20, Tuesday 14-17 | 17-20, Thursday 14-17 | 17-20, Friday 14-17 | 17-20",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
    ],
    activities: ["Organizing excursions"],
    languages: ["German", "Russian", "Ukrainian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:39.067580Z",
    updated_at: "2025-12-23T18:30:00.416922Z",
    category: "Sport activities",
    category_id: 5,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5536,
    title: "Help you find accommodation",
    vo_information:
      "We have several residents who would like help finding their own apartment (where do you look for them, what documents do I have to prepare/apply for, how do I apply, what do I take with me to the apartment inspection, etc. ",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Treptow"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Miscellanious"],
    languages: ["Arabic", "English", "German", "Farsi", "Russian", "Turkish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-16T16:00:10.945892Z",
    updated_at: "2025-12-16T17:22:41.679967Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-16T15:24:00Z",
  },
  {
    id: 5903,
    title: "NEW conversations, going for walks. Arabic or English.",
    vo_information:
      "We're looking for a person who could go for a walk with a man. He speaks Arabic and English. It would be wonderful if a person could come to him from time to time, visit him or take him on a walk. He is visually impaired and therefore more likely to have limited mobility when situations arise outside.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Wedding"],
    schedule_str:
      "Wednesday 14-17 | 17-20 | 11-14, Monday 14-17 | 17-20 | 11-14, Tuesday 14-17 | 17-20 | 11-14, Thursday 14-17 | 17-20 | 11-14, Friday 14-17 | 17-20 | 11-14, Saturday 14-17 | 17-20 | 11-14, Sunday 14-17 | 17-20 | 11-14, Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 2,
        time_slot: "11-14",
      },
      {
        day: 4,
        time_slot: "11-14",
      },
      {
        day: 5,
        time_slot: "11-14",
      },
      {
        day: 6,
        time_slot: "14-17",
      },
      {
        day: 7,
        time_slot: "14-17",
      },
      {
        day: 3,
        time_slot: "11-14",
      },
      {
        day: 6,
        time_slot: "17-20",
      },
      {
        day: 7,
        time_slot: "17-20",
      },
      {
        day: 6,
        time_slot: "11-14",
      },
      {
        day: 7,
        time_slot: "11-14",
      },
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
    ],
    activities: ["Activities for men"],
    languages: ["Arabic", "English"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:32.964545Z",
    updated_at: "2025-12-23T18:29:58.958432Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-23T15:29:00Z",
  },
  {
    id: 5839,
    title: "Accompaniment to the pediatrician",
    vo_information: null,
    accomp_information:
      "Translation during the investigation (better in Georgian because both parents speak Georgian. Only the father speaks in Russian.). Sana PAEDIATRIC PRACTICE. East entrance, ground floor",
    accomp_translation: "deutsche",
    accomp_datetime: "2026-01-05T12:00:00Z",
    berlin_locations: ["Marzahn"],
    schedule_str: "",
    datetime_str: null,
    timeslots: [],
    activities: ["Accompanying to doctors'"],
    languages: ["Georgian", "Russian"],
    skills: [],
    status: "Search in process",
    opportunity_type: "accompanying",
    created_at: "2025-12-23T11:00:17.160838Z",
    updated_at: "2025-12-23T11:08:01.534877Z",
    category: "Accompany a Refugee",
    category_id: 6,
    last_edited_time_notion: "2025-12-23T10:34:00Z",
  },
  {
    id: 5769,
    title: "Tutoring in German, math",
    vo_information: "We need tutoring for our students, primarily in German and math",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Schöneberg", "Tempelhof"],
    schedule_str:
      "Monday 14-17 | 17-20, Tuesday 14-17 | 17-20, Wednesday 17-20 | 14-17, Thursday 17-20 | 14-17, Friday 17-20 | 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["German", "Russian", "Ukrainian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-22T13:00:09.254945Z",
    updated_at: "2025-12-22T14:07:27.706478Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-22T12:58:00Z",
  },
  {
    id: 5343,
    title: "FrauenCafe",
    vo_information:
      "We would like to organize a women's cafe (language cafe) in our institution once a week. To this end, we are looking for committed volunteers who enjoy talking and motivate others to share their stories. We want to speak German together in a relaxed atmosphere, learn from each other and exchange ideas.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Wednesday 14-17, Monday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17, Occasional Weekdays",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Language café"],
    languages: [
      "Arabic",
      "English",
      "French",
      "Georgian",
      "German",
      "Farsi",
      "Russian",
      "Turkish",
      "Ukrainian",
      "Vietnamese",
    ],
    skills: ["Public speaking"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-10T17:00:11.464099Z",
    updated_at: "2025-12-10T17:09:05.677100Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-10T16:20:00Z",
  },
  {
    id: 5344,
    title: "Sprachcafé",
    vo_information:
      "We would like volunteers to talk to residents in a language café and help with grammar exercises. We now have a language café every Wednesday between 14:00 and 16:00.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Mitte"],
    schedule_str: "Wednesday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
    ],
    activities: ["Language café"],
    languages: ["Arabic", "English", "German", "Farsi", "Polish", "Russian", "Spanish", "Turkish", "Ukrainian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-10T17:00:11.801039Z",
    updated_at: "2025-12-10T17:09:05.958367Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-10T16:38:00Z",
  },
  {
    id: 5792,
    title: "Volunteers playing soccer with the children",
    vo_information:
      "It would be great if someone came over the weekend or before nightfall. We have a concrete soccer field and there is a need to play all year round. There is no one for this at the moment; two people are also welcome to take over.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Neukölln"],
    schedule_str: "Saturday 14-17 | 17-20, Sunday 14-17 | 17-20, Occasional Weekdays",
    datetime_str: null,
    timeslots: [
      {
        day: 6,
        time_slot: "14-17",
      },
      {
        day: 7,
        time_slot: "14-17",
      },
      {
        day: 6,
        time_slot: "17-20",
      },
      {
        day: 7,
        time_slot: "17-20",
      },
    ],
    activities: ["Sports"],
    languages: ["Arabic", "German", "Farsi"],
    skills: ["Football"],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-22T15:00:22.946895Z",
    updated_at: "2025-12-22T15:37:38.049088Z",
    category: "Sport activities",
    category_id: 5,
    last_edited_time_notion: "2025-12-22T14:40:00Z",
  },
  {
    id: 5911,
    title: "Crafting & painting, reading mentors ",
    vo_information:
      "We are looking for volunteers who can help us with childcare and other activities for children and young people.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Spandau"],
    schedule_str: "Wednesday 14-17 | 11-14, Monday 14-17 | 11-14, Tuesday 14-17 | 11-14, Thursday 14-17 | 11-14",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 2,
        time_slot: "11-14",
      },
      {
        day: 4,
        time_slot: "11-14",
      },
      {
        day: 3,
        time_slot: "11-14",
      },
    ],
    activities: ["Playing board games"],
    languages: ["English", "German", "Russian", "Ukrainian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:38.373130Z",
    updated_at: "2025-12-23T18:29:59.590531Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-23T15:30:00Z",
  },
  {
    id: 5912,
    title: "Dancing for girls aged 7-12",
    vo_information: "Rhytmic movement for girls aged 7-12 In the main hall of the property",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Monday 14-17, Wednesday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Sports"],
    languages: ["English", "German"],
    skills: ["Dance"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:38.756956Z",
    updated_at: "2025-12-23T18:30:00.286042Z",
    category: "Sport activities",
    category_id: 5,
    last_edited_time_notion: "2025-12-23T15:30:00Z",
  },
  {
    id: 5516,
    title: "Tutoring/learning support for the MSA",
    vo_information:
      "A 17-year-old young person needs support in learning for the MSA. If possible, tutoring should take place once a week at the accommodation in Reinickendorf (Eichborndamm). Experience with tutoring is an advantage.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Reinickendorf"],
    schedule_str:
      "Monday 17-20, Thursday 17-20, Tuesday 17-20, Wednesday 17-20, Saturday 14-17 | 11-14, Sunday 14-17 | 11-14",
    datetime_str: null,
    timeslots: [
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
      {
        day: 6,
        time_slot: "14-17",
      },
      {
        day: 7,
        time_slot: "14-17",
      },
      {
        day: 6,
        time_slot: "11-14",
      },
      {
        day: 7,
        time_slot: "11-14",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["German", "Russian", "Kurmanji"],
    skills: ["Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-16T12:00:12.263500Z",
    updated_at: "2025-12-16T12:08:56.161409Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-16T11:51:00Z",
  },
  {
    id: 5541,
    title: "telephone service",
    vo_information:
      "Support the team by answering and forwarding incoming calls. At a fixed time of the week, incoming calls should be answered and forwarded to colleagues. It should take place at a fixed time during our core working hours, i.e. Mon-Fr between 9 a.m. and 4 p.m. The duration is flexible, starting at 2 hours. ",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Tempelhof"],
    schedule_str:
      "Wednesday 14-17 | 08-11, Monday 14-17 | 11-14 | 08-11, Tuesday 14-17, Thursday 14-17 | 11-14 | 08-11, Friday 14-17 | 11-14 | 08-11",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 4,
        time_slot: "11-14",
      },
      {
        day: 5,
        time_slot: "11-14",
      },
      {
        day: 1,
        time_slot: "08-11",
      },
      {
        day: 3,
        time_slot: "08-11",
      },
      {
        day: 4,
        time_slot: "08-11",
      },
      {
        day: 5,
        time_slot: "08-11",
      },
    ],
    activities: ["Miscellanious"],
    languages: ["German"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-16T16:00:13.555282Z",
    updated_at: "2025-12-16T17:22:41.939639Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-16T15:42:00Z",
  },
  {
    id: 5542,
    title: "Homework help for kids in GU",
    vo_information:
      "Helping school children (primary school children up to 12 years of age) with their homework (various subjects as required).\nIf there are several children, homework help is in the group. However, it can also happen that only one child comes. Supervision takes place in pairs.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Tempelhof"],
    schedule_str: "Wednesday 14-17, Monday 14-17, Thursday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["Arabic", "German", "Farsi"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-16T16:00:13.654659Z",
    updated_at: "2025-12-16T17:22:42.202575Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-16T15:43:00Z",
  },
  {
    id: 5752,
    title: "Support with childcare",
    vo_information: "We're looking for volunteers to take care of the kids, play with them and have a good time.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Monday 14-17, Tuesday 14-17, Wednesday 14-17, Thursday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Daycare"],
    languages: [
      "Arabic",
      "English",
      "French",
      "Georgian",
      "German",
      "Farsi",
      "Russian",
      "Turkish",
      "Ukrainian",
      "Vietnamese",
    ],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-22T11:00:10.439409Z",
    updated_at: "2025-12-22T14:07:29.738660Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-22T10:17:00Z",
  },
  {
    id: 5754,
    title: "Everyday support from volunteer mentors in Berlin Xenion",
    vo_information:
      "The project is being implemented by the XENION psychosocial center as part of a holistic approach. Volunteers are professionally supervised by the full-time team, can attend training courses and an activity program and, if necessary, seek individual supervision.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Mitte", "Neukölln", "Prenzlauer Berg", "Schöneberg", "Tempelhof"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Mentorship"],
    languages: ["Arabic", "French", "German", "Farsi", "Russian", "Turkish", "Ukrainian"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-22T11:00:11.132571Z",
    updated_at: "2025-12-22T14:07:30.033538Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-22T10:16:00Z",
  },
  {
    id: 4683,
    title: "Homework help welcome class",
    vo_information:
      "The children (the girls are (almost) 12 and 14 years old) have just arrived in Germany (September) due to family reunification and have problems with homework and need a little help 1-3 times a week would be great or as needed.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Neukölln"],
    schedule_str: "Wednesday 14-17, Monday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["French"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-11-19T11:00:11.686621Z",
    updated_at: "2025-11-19T11:56:39.503987Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-11-19T10:43:00Z",
  },
  {
    id: 5914,
    title: "NEW Support for the women's café to promote the German language.",
    vo_information:
      "Supporting women in a women's café, which focuses primarily on promoting the German language. Language exercises and explanations of the German language, answering women's questions about the German language.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Köpenick", "Treptow"],
    schedule_str: "Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Language café"],
    languages: ["German"],
    skills: ["Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:39.352531Z",
    updated_at: "2025-12-23T18:30:00.622230Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5712,
    title: "Tutoring for school children",
    vo_information: null,
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Monday 14-17, Tuesday 14-17, Wednesday 14-17, Thursday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["German"],
    skills: ["Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-19T15:00:13.655603Z",
    updated_at: "2025-12-19T15:33:49.223999Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-19T14:54:00Z",
  },
  {
    id: 5713,
    title: "piano lessons for children, childcare in the youth room",
    vo_information:
      "We have a youth room recently and would love to have a few volunteers who offer activities for children. We also have a few keyboards for piano and would be happy to welcome volunteers who want to do something in the area.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Monday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17, Wednesday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Daycare"],
    languages: ["English", "French", "German", "Russian", "Turkish"],
    skills: ["Painting", "Teaching", "Piano"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-19T15:00:14.073952Z",
    updated_at: "2025-12-19T15:33:49.533320Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-19T14:54:00Z",
  },
  {
    id: 5716,
    title: "Support the women's café ",
    vo_information:
      "Are we looking for a woman who would like to help out with Frauencafé? Both support in preparation, implementation and follow-up. She is welcome to contribute her idea. A plus would be if the person can also speak Turkish, Russian, Georgian or Arabic, but that is not a must",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Tuesday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 2,
        time_slot: "14-17",
      },
    ],
    activities: ["Mentorship"],
    languages: ["Arabic", "Georgian", "German", "Russian", "Turkish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-19T15:00:17.468442Z",
    updated_at: "2025-12-19T15:33:49.777040Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-19T14:54:00Z",
  },
  {
    id: 5915,
    title: "NEW Support for sorting documents",
    vo_information: "Sort and explain documents and documents. Help to fill out if necessary.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Neukölln"],
    schedule_str: "Occasional Weekdays",
    datetime_str: null,
    timeslots: [],
    activities: [null],
    languages: ["Arabic", "German", "Farsi", "Russian", "Turkish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:39.653666Z",
    updated_at: "2025-12-23T18:30:00.819609Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5916,
    title: "Creative offers for children",
    vo_information: "Plan and carry out a craft activity (crafternoons) for children aged 6-11 every week.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Prenzlauer Berg"],
    schedule_str: "Thursday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 4,
        time_slot: "14-17",
      },
    ],
    activities: ["Daycare"],
    languages: ["Arabic", "German", "Farsi", "Russian", "Turkish", "Ukrainian", "Kurmanji"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:40.365374Z",
    updated_at: "2025-12-23T18:30:01.080966Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5917,
    title: "Accompanying our activities",
    vo_information:
      "We are looking for committed volunteers who want to: accompany participants on walks, museum visits, trips. To conduct simple conversations in German and to help you learn the language. To contribute and co-create ideas for activities. Joy of contact with people, an open heart.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Berlin"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Organizing excursions"],
    languages: ["German"],
    skills: ["Public speaking"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:40.670011Z",
    updated_at: "2025-12-23T18:30:01.802977Z",
    category: "Sport activities",
    category_id: 5,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5918,
    title: "NEW Support for learning German",
    vo_information:
      "We are looking for someone to help our client learn German. He has visual impairment and would like the support to be provided at home.\nHe would also occasionally need assistance with directions and accompaniment to the doctor or office. However, the focus is on learning German. He lives in Treptow-Köpenick and speaks French, Spanish and English.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Köpenick", "Treptow"],
    schedule_str: "Occasional Weekdays",
    datetime_str: null,
    timeslots: [],
    activities: ["Mentorship"],
    languages: ["English", "French", "Spanish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:41.653660Z",
    updated_at: "2025-12-23T18:30:02.073756Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5920,
    title: "Women's cafe",
    vo_information: "A person who can run the women's cafe in Russian or Ukrainian.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Charlottenburg"],
    schedule_str: "Occasional Weekdays | Weekends",
    datetime_str: null,
    timeslots: [],
    activities: ["Activities for women"],
    languages: ["English", "German", "Russian", "Ukrainian"],
    skills: ["Teaching", "Public speaking"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:44.755154Z",
    updated_at: "2025-12-23T18:30:02.303512Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5921,
    title: "Child care small activities ",
    vo_information: "A person who plays with the children and offers small activities.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Charlottenburg"],
    schedule_str: "Occasional Weekdays",
    datetime_str: null,
    timeslots: [],
    activities: ["Arts & Crafts"],
    languages: ["German", "Russian", "Ukrainian"],
    skills: ["Drawing", "Painting", "Sewing", "Public speaking", "Decorating"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T16:00:45.863570Z",
    updated_at: "2025-12-23T18:30:02.511800Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-23T15:31:00Z",
  },
  {
    id: 5418,
    title: "Support with childcare",
    vo_information: "Organize activities for children and support childcare workers in planning craft activities.  ",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Treptow"],
    schedule_str: "Tuesday 14-17, Wednesday 14-17, Thursday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
    ],
    activities: ["Daycare"],
    languages: ["Dari", "French", "Georgian", "Turkish"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-12T14:00:10.083147Z",
    updated_at: "2025-12-12T14:29:24.313305Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-12T13:56:00Z",
  },
  {
    id: 5420,
    title: "Recreational and/or leisure activities for women",
    vo_information:
      "The aim is to offer women who live in the Kaklower Weg joint venture (all with small children) every kind of leisure activity. It would be ideal once a week but I remain at your full disposal for any advice.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Köpenick", "Treptow"],
    schedule_str:
      "Wednesday 14-17 | 17-20, Monday 14-17 | 17-20, Tuesday 14-17 | 17-20, Thursday 14-17 | 17-20, Friday 14-17 | 17-20",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
    ],
    activities: ["Activities for women"],
    languages: ["German", "Turkish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-12T14:00:10.813343Z",
    updated_at: "2025-12-12T14:29:24.355482Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-12T13:57:00Z",
  },
  {
    id: 4615,
    title: "Accompaniment/guide for women's or men's café in the accommodation",
    vo_information:
      "Once a week, there should be a women's or men's cafe for residents in our accommodation. The offer should take place on a weekday, starting around 16h or later for about two hours. It would be nice if several people (at least 2 per café) could be found accompanying the respective café. The café could be used as a language café, as an opportunity to exchange ideas, meet and develop ideas together on how to spend time together. Volunteer Coordination will be happy to answer any questions you may have.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Occasional Weekdays",
    datetime_str: null,
    timeslots: [],
    activities: ["Mentorship"],
    languages: ["Arabic", "Armenian", "German", "Farsi", "Russian", "Turkish", "Vietnamese"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-11-17T16:00:13.774299Z",
    updated_at: "2025-11-17T16:58:59.854674Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-11-17T15:59:00Z",
  },
  {
    id: 5121,
    title: "Volunteers to help with our clothing store",
    vo_information:
      "The tasks are: \n- creating a welcoming and friendly atmosphere for residents who visit the clothing room\n- Assistance in handing out clothes to refugees",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Köpenick", "Treptow"],
    schedule_str: "Thursday 11-14",
    datetime_str: null,
    timeslots: [
      {
        day: 4,
        time_slot: "11-14",
      },
    ],
    activities: ["Clothing Sorting"],
    languages: ["Arabic", "English", "German", "Farsi", "Russian", "Turkish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-03T14:00:19.463626Z",
    updated_at: "2025-12-03T14:05:12.709931Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-03T13:43:00Z",
  },
  {
    id: 5643,
    title: "Weekly leisure activities for young people",
    vo_information:
      "We are looking for volunteers who offer leisure activities for young people in the youth room on fixed days a week, e.g. painting T-shirts or bags, crafts and upcycling projects, photo projects, music workshops, learning instruments, self-defense. Young people often also contribute ideas to projects themselves. Since the group to be supervised is minors, the four-eyes principle applies. It would therefore have to be two volunteers.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Tempelhof"],
    schedule_str: "Wednesday 14-17, Monday 14-17, Tuesday 14-17, Thursday 14-17, Friday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
    ],
    activities: ["Miscellanious"],
    languages: ["Arabic", "German", "Farsi", "Russian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T11:00:27.062539Z",
    updated_at: "2025-12-18T11:26:42.518989Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-18T10:19:00Z",
  },
  {
    id: 5761,
    title: "Support in the clothing room",
    vo_information:
      "We are looking for someone for our clothing store (sort out donations and make them available for residents). That would be on Wednesdays 11-13:00.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Lichtenberg"],
    schedule_str: "Wednesday 11-14 | 08-11",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "11-14",
      },
      {
        day: 3,
        time_slot: "08-11",
      },
    ],
    activities: ["Clothing Sorting"],
    languages: ["Arabic", "Georgian", "German", "Farsi", "Russian"],
    skills: ["Management"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-22T13:00:07.882308Z",
    updated_at: "2025-12-22T14:07:30.857670Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-22T12:47:00Z",
  },
  {
    id: 5649,
    title: "Organize games for children in the playroom in Neukölln",
    vo_information:
      "Languages are not a must, but most members of the team speak German.\nPlayroom is a project that has been running for more than a year. There is a group of volunteers who organize activities for children on Tuesday and Wednesday evenings. Since there is no all-day childcare at the hotel, the more activities can be organized the more volunteers there are.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Neukölln"],
    schedule_str: "Tuesday 17-20, Wednesday 17-20",
    datetime_str: null,
    timeslots: [
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
    ],
    activities: ["Daycare"],
    languages: ["Arabic", "English", "German", "Russian", "Turkish"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-18T11:00:28.082398Z",
    updated_at: "2025-12-18T11:26:43.556101Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-18T10:21:00Z",
  },
  {
    id: 5865,
    title: "childcare",
    vo_information:
      "Until recently, we had childcare from Turning Point/Springboard, which tinkered, painted and played with small children three times a week in our accommodation. Unfortunately, this position has just been removed and as of January we will no longer have anyone there. It would be great if we could find 1 or 2 volunteers who enjoy hands-on work with children. The times clicked on are only options, weekdays between 15:00 and 19:00 would be appropriate, once or twice a week, which must then be discussed with the children.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Moabit"],
    schedule_str:
      "Wednesday 14-17 | 17-20, Monday 14-17 | 17-20, Tuesday 14-17 | 17-20, Thursday 14-17 | 17-20, Friday 14-17 | 17-20",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
    ],
    activities: ["Daycare"],
    languages: ["Arabic", "German", "Farsi", "Turkish"],
    skills: ["Woodworking", "Drawing", "Painting", "Decorating"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-23T13:00:15.132758Z",
    updated_at: "2025-12-23T13:00:53.372736Z",
    category: "Childcare",
    category_id: 2,
    last_edited_time_notion: "2025-12-23T12:53:00Z",
  },
  {
    id: 5523,
    title: "Homework assistance",
    vo_information:
      "Small groups of children provide homework help (for children between 6 and 15 years of age) in various subjects such as mathematics, English and German.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Köpenick", "Treptow"],
    schedule_str:
      "Wednesday 14-17 | 17-20, Monday 14-17 | 17-20, Tuesday 14-17 | 17-20, Thursday 14-17 | 17-20, Friday 14-17 | 17-20",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "14-17",
      },
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 1,
        time_slot: "17-20",
      },
      {
        day: 4,
        time_slot: "17-20",
      },
      {
        day: 5,
        time_slot: "17-20",
      },
      {
        day: 2,
        time_slot: "17-20",
      },
      {
        day: 3,
        time_slot: "17-20",
      },
    ],
    activities: ["Assist with homework"],
    languages: ["Arabic", "Georgian", "German", "Farsi", "Russian", "Turkish"],
    skills: ["Teaching"],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-16T13:00:18.649265Z",
    updated_at: "2025-12-16T13:16:24.685300Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-16T12:56:00Z",
  },
  {
    id: 5463,
    title: "Interpreter for an ophthalmology appointment",
    vo_information: null,
    accomp_information: "ophthalmology, follow-up",
    accomp_translation: "deutsche",
    accomp_datetime: "2025-12-23T07:10:00Z",
    berlin_locations: ["Steglitz"],
    schedule_str: "",
    datetime_str: null,
    timeslots: [],
    activities: ["Accompanying to doctors'"],
    languages: ["Russian"],
    skills: [],
    status: "Search in process",
    opportunity_type: "accompanying",
    created_at: "2025-12-15T13:00:10.707165Z",
    updated_at: "2025-12-15T13:51:09.023649Z",
    category: "Accompany a Refugee",
    category_id: 6,
    last_edited_time_notion: "2025-12-15T12:25:00Z",
  },
  {
    id: 5720,
    title: "German lessons for women",
    vo_information:
      "We need a German teacher or someone who would be willing to offer German conversation for the women in the accommodation.\nThe dates:\n- Monday: 10:00 - 12:00\n- Tuesday: 10:00 - 12:00\n- Wednesday: 10:00 - 12:00\n- Thursday: 10:00 - 12:00",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Pankow"],
    schedule_str: "Monday 11-14 | 08-11, Tuesday 11-14 | 08-11, Wednesday 11-14 | 08-11, Thursday 11-14 | 08-11",
    datetime_str: null,
    timeslots: [
      {
        day: 1,
        time_slot: "11-14",
      },
      {
        day: 2,
        time_slot: "11-14",
      },
      {
        day: 4,
        time_slot: "11-14",
      },
      {
        day: 3,
        time_slot: "11-14",
      },
      {
        day: 1,
        time_slot: "08-11",
      },
      {
        day: 2,
        time_slot: "08-11",
      },
      {
        day: 3,
        time_slot: "08-11",
      },
      {
        day: 4,
        time_slot: "08-11",
      },
    ],
    activities: ["Language café"],
    languages: ["Arabic", "German", "Farsi", "Turkish"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-19T16:00:13.158664Z",
    updated_at: "2025-12-19T16:19:42.457089Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-19T15:31:00Z",
  },
  {
    id: 5722,
    title:
      "NEW RU Translation in our accommodation, preferably regularly once a week, e.g. every Tuesday or Thursday 13-15:00",
    vo_information: "Language teaching during office hours in social services",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Pankow"],
    schedule_str: "Tuesday 14-17, Thursday 14-17",
    datetime_str: null,
    timeslots: [
      {
        day: 2,
        time_slot: "14-17",
      },
      {
        day: 4,
        time_slot: "14-17",
      },
    ],
    activities: ["Translation at Accommodation Centers"],
    languages: ["Russian"],
    skills: [],
    status: "Search in process",
    opportunity_type: "volunteering",
    created_at: "2025-12-19T16:00:14.155754Z",
    updated_at: "2025-12-19T16:19:42.786249Z",
    category: "German Language Support",
    category_id: 1,
    last_edited_time_notion: "2025-12-19T15:12:00Z",
  },
  {
    id: 5724,
    title: "Garment Room Volunteer",
    vo_information:
      "Open, look after and close the clothing store, sort donations of clothes. \n\nWe are currently primarily looking for volunteers who can step in as a substitute when our regular volunteers are ill and those who are free on Fridays from 1 pm to 3 pm to look after the clothing room for women and children.\n\nThe clothing stores now have parallel opening hours, Wednesday and Friday from 1 to 3 p.m. We always need one person for the men's clothing room, two are ideal for women and children because there are two separate containers there.",
    accomp_information: null,
    accomp_translation: null,
    accomp_datetime: null,
    berlin_locations: ["Tempelhof"],
    schedule_str: "Wednesday 14-17 | 11-14, Friday 14-17 | 11-14",
    datetime_str: null,
    timeslots: [
      {
        day: 3,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "14-17",
      },
      {
        day: 5,
        time_slot: "11-14",
      },
      {
        day: 3,
        time_slot: "11-14",
      },
    ],
    activities: ["Clothing Sorting"],
    languages: ["Arabic", "English", "French", "German", "Farsi", "Romanes", "Russian", "Turkish", "Ukrainian"],
    skills: [],
    status: "Volunteers Needed",
    opportunity_type: "volunteering",
    created_at: "2025-12-19T16:00:15.160088Z",
    updated_at: "2025-12-19T16:19:43.213433Z",
    category: "Skills Based Volunteering",
    category_id: 3,
    last_edited_time_notion: "2025-12-19T15:20:00Z",
  },
] as unknown as OpportunityApi[];
