import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { I18nProvider } from '../config/i18next'
import StyledComponentsRegistry from '@/lib/styled-components-registry'
import { ScreenTypes } from '@/config/constants'
import { headers } from 'next/headers'
import { DeviceProvider } from '@/context/DeviceContext'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const getInitialDeviceType = async () => {
  const headersList = await headers()
  const deviceTypeHeader = headersList.get('x-device-type')

  switch (deviceTypeHeader) {
    case 'mobile':
      return ScreenTypes.MOBILE
    case 'tablet':
      return ScreenTypes.TABLET
    default:
      return ScreenTypes.DESKTOP
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialScreenType = await getInitialDeviceType()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StyledComponentsRegistry>
          <DeviceProvider initialScreenType={initialScreenType}>
            <I18nProvider>{children}</I18nProvider>
          </DeviceProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
